// Blueprint OS marketing strategies — editorial content, not data
import type { Strategy } from "./types";

export const strategies: Strategy[] = [
  {
    id: "s1",
    title: "Build-in-Public Thread Series",
    description:
      "Weekly Twitter/X threads documenting real product decisions, bugs, revenue milestones, and growth. This compounds over time — transparency builds trust with developers and founders.",
    impact: "high",
    effort: "medium",
    timeframe: "Ongoing, weekly",
    tactics: [
      "Every Monday: share 1 real metric (users, ARR, churn)",
      "Every Wednesday: technical decision thread with pros/cons",
      "Every Friday: week recap with honest reflection",
      "Cross-post top threads as Instagram carousels",
    ],
    platform: "twitter",
    category: "content",
    status: "active",
  },
  {
    id: "s2",
    title: "TikTok Viral Hook Strategy",
    description:
      'TikTok\'s algorithm heavily rewards early retention. Blueprint OS demos are inherently visual and surprising — perfect for "POV: your AI actually does X" format videos.',
    impact: "high",
    effort: "medium",
    timeframe: "3-4 videos/week",
    tactics: [
      'Use "POV" and "Watch what happens when..." hooks in first 2 seconds',
      "Demo one specific feature per video — no overloading",
      "End every video with a CTA to waitlist/signup link in bio",
      "Respond to every comment in first hour (algo boost)",
      "Post between 6-9 PM local time for max reach",
    ],
    platform: "tiktok",
    category: "content",
    status: "active",
  },
  {
    id: "s3",
    title: "Influencer Co-creation Program",
    description:
      "Partner with 5-10 micro-influencers (10K-100K followers) in the productivity/indie-hacker/founder space. Give them early access and let them document their experience authentically.",
    impact: "high",
    effort: "high",
    timeframe: "1-2 months to set up",
    tactics: [
      "Identify top 20 target accounts from Lead Tracker",
      "Send personalized DMs with lifetime free access offer",
      'Ask for honest "I tried this for a week" content — no scripts',
      "Provide a referral link for each partner with revenue share",
      "Weekly check-ins to help them get the most from the product",
    ],
    platform: "all",
    category: "partnerships",
    status: "planned",
  },
  {
    id: "s4",
    title: "Instagram Carousel Authority Content",
    description:
      "Instagram carousels get 3x more reach than single images. Educational carousels about AI productivity, workflow design, and startup ops position Blueprint OS as a thought leader.",
    impact: "medium",
    effort: "medium",
    timeframe: "2-3 carousels/week",
    tactics: [
      'Topics: "5 signs your productivity stack is broken", "How top founders use AI"',
      "Always start slide 1 with a bold controversial statement",
      "Slide 2-8: evidence, examples, screenshots",
      "Last slide: CTA + save prompt",
      "Repurpose from long-form blog content for efficiency",
    ],
    platform: "instagram",
    category: "content",
    status: "active",
  },
  {
    id: "s5",
    title: "Twitter/X Reply Guy Strategy",
    description:
      "Being visible in conversations started by larger accounts in your niche is free distribution. Thoughtful replies to large founders/builders get seen by their audiences.",
    impact: "medium",
    effort: "low",
    timeframe: "Daily, 15-30 min",
    tactics: [
      "Follow 50 accounts in your target audience's orbit",
      "Enable notifications for their tweets",
      "Reply within first 10 minutes of their posts for visibility",
      "Add genuine value — never promotional",
      '"Pinned reply" worthy comments that get engagement',
    ],
    platform: "twitter",
    category: "engagement",
    status: "active",
  },
  {
    id: "s6",
    title: "ProductHunt & Hacker News Launches",
    description:
      "Timed launches on PH and HN drive massive spikes in signups and social proof. Blueprint OS has a compelling story — AI OS built by a solo founder in public.",
    impact: "high",
    effort: "high",
    timeframe: "One-time + quarterly hunts",
    tactics: [
      'Build a "coming soon" PH page and collect upvote pledges',
      "Schedule launch for Tuesday at 12:01 AM PST",
      "Prep 10 early supporters to comment in first hour",
      'Write a detailed "Show HN" post for Hacker News same day',
      "Document the launch in a Twitter thread in real-time",
    ],
    platform: "all",
    category: "growth",
    status: "planned",
  },
  {
    id: "s7",
    title: "User Story Content Series",
    description:
      'Real user testimonials converted into short-form content. "How [user] went from X to Y using Blueprint OS" stories perform extremely well across all platforms.',
    impact: "medium",
    effort: "low",
    timeframe: "Weekly",
    tactics: [
      "Interview power users every 2 weeks via short Loom/async",
      "Turn stories into Twitter threads + IG carousels + TikTok voiceovers",
      "Get explicit approval and tag users — they share to their audience",
      "Create a featured users highlight on Instagram",
    ],
    platform: "all",
    category: "content",
    status: "planned",
  },
  {
    id: "s8",
    title: "Paid Twitter/X Ads — Amplify Top Posts",
    description:
      "Don't create new ad creative — amplify your organic posts that already have traction. This is the \"double down on what works\" approach that keeps CAC low.",
    impact: "medium",
    effort: "low",
    timeframe: "Ongoing, $500-1K/mo budget",
    tactics: [
      "Wait for organic posts to hit 4%+ engagement before boosting",
      "Target: founders, engineers, PM personas on Twitter/X",
      "Use conversation-style ads, not traditional banners",
      "A/B test 2-3 variations of top posts",
      "Cap spend at $50/day per post boost",
    ],
    platform: "twitter",
    category: "paid",
    status: "planned",
  },
];
